import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profilesRouter from "./profiles";
import streaksRouter from "./streaks";
import progressRouter from "./progress";
import vocabularyRouter from "./vocabulary";
import contactRouter from "./contact";
import aiRouter from "./ai";
import practiceAiRouter from "./practiceAi";
import practiceItemsRouter from "./practiceItems";
import adminRouter from "./admin";
import adminInvitesRouter from "./adminInvites";
import auditRouter from "./audit";
import subscriptionRouter from "./subscription";
import stripeRouter from "./stripe";
import revenuecatWebhookRouter from "./revenuecatWebhook";
import echoMemoryRouter from "./echoMemory";
import dailySessionsRouter from "./dailySessions";
import learningContentRouter from "./learningContent";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profilesRouter);
router.use(streaksRouter);
router.use(progressRouter);
router.use(vocabularyRouter);
router.use(contactRouter);
router.use(aiRouter);
router.use(practiceAiRouter);
router.use(practiceItemsRouter);
router.use(adminRouter);
router.use(adminInvitesRouter);
router.use(auditRouter);
router.use(subscriptionRouter);
router.use(stripeRouter);
router.use("/revenuecat/webhook", revenuecatWebhookRouter);
router.use(echoMemoryRouter);
router.use(dailySessionsRouter);
router.use(learningContentRouter);

export default router;
